"""Auto-generated by notebooks/phase0_eda.ipynb. Do not edit by hand."""

# COCO category_ids actually present in the FathomNet 2026 train split.
# These are NOT contiguous (gaps at 12, 14, 16, 18, 21, 23, 31, 34, 39).
COCO_CAT_IDS: list[int] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 20, 22, 24, 25, 26, 27, 28, 29, 30, 32, 33, 35, 36, 37, 38, 40, 41]

# Two-way mapping. Use cat_id_to_idx for training; idx_to_cat_id when
# writing the submission CSV (the evaluator expects the original COCO id).
cat_id_to_idx: dict[int, int] = {1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 13: 11, 15: 12, 17: 13, 19: 14, 20: 15, 22: 16, 24: 17, 25: 18, 26: 19, 27: 20, 28: 21, 29: 22, 30: 23, 32: 24, 33: 25, 35: 26, 36: 27, 37: 28, 38: 29, 40: 30, 41: 31}
idx_to_cat_id: dict[int, int] = {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 15, 13: 17, 14: 19, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 27, 21: 28, 22: 29, 23: 30, 24: 32, 25: 33, 26: 35, 27: 36, 28: 37, 29: 38, 30: 40, 31: 41}

# Index → human-readable name (for plots, taxonomy ops, and config files).
idx_to_name: dict[int, str] = {0: 'amphipod', 1: 'anemone', 2: 'barnacle', 3: 'benthic worm', 4: 'bivalve', 5: 'black coral', 6: 'bony fish', 7: 'brittle star', 8: 'calycophoran siphonophore', 9: 'chiton', 10: 'crab', 11: 'feather star', 12: 'hydroid', 13: 'isopod', 14: 'jelly', 15: 'larvacean', 16: 'octopus', 17: 'physonect siphonophore', 18: 'pyrosome', 19: 'sea cucumber', 20: 'sea fan', 21: 'sea pen', 22: 'sea slug', 23: 'sea snail', 24: 'sea squirt', 25: 'sea star', 26: 'shrimp', 27: 'soft coral', 28: 'sponge', 29: 'squat lobster', 30: 'stony coral', 31: 'urchin'}

NUM_CLASSES: int = len(COCO_CAT_IDS)
