"""Estimate the PU class prior pi for Phase 3 EXP 3.1 (CPU-only, ~30 sec).

Block reference: E.2 in master_checklist.txt.

Usage
-----
    python scripts/build_pu_prior.py
    python scripts/build_pu_prior.py --method annotation_rate
    python scripts/build_pu_prior.py --train-json data/raw/train_dataset.json \\
        --out notes/phase3_pi_estimate.md

What this does
--------------
Reads train_dataset.json, computes the PU class prior pi via
src.pu_loss.estimate_pu_prior(), and writes a Markdown report to
notes/phase3_pi_estimate.md (or the path given via --out).

This is the prerequisite for E.3 -- the KiryoPULoss constructor needs
pi to instantiate. We compute it once, save it to a file, then read
it from the file at training time.

Why a separate script (instead of just calling the function inline at
training time)
--------------
1. The estimate is dataset-wide. It should be computed ONCE per dataset
   version, NOT every time we kick off a training run.
2. Writing it to a file creates an audit trail -- if pi differs across
   experiments, we know we're comparing apples to oranges.
3. The Markdown report is paper material (justifies the choice of pi
   in the methodology section of the working notes paper).

Output
------
A Markdown file with:
- The estimated pi (the headline number)
- Per-image area-fraction distribution (mean, median, p5, p95)
- Sanity checks (range, image count, annotation count)
- Recommended PU loss config (sane defaults given pi)

The same numerical pi value is also printed to stdout for piping into
shell variables.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.pu_loss import estimate_pu_prior


def _gather_per_image_stats(train_json_path: Path) -> dict:
    """Gather extra stats for the Markdown report (annotation count, image count)."""
    with train_json_path.open() as f:
        coco = json.load(f)
    return {
        "n_images": len(coco["images"]),
        "n_annotations": len(coco["annotations"]),
        "n_categories": len(coco.get("categories", [])),
    }


def _format_report(
    pi: float,
    method: str,
    train_json_path: Path,
    extra_stats: dict,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S %Z").strip()
    if pi < 0.05:
        risk = "LOW (pi small -> non-negative trick fires often, expect Kiryo to clip negative-risk a lot)"
    elif pi > 0.3:
        risk = "HIGH (pi large -> close to standard BCE, Kiryo PU adds little)"
    else:
        risk = "MEDIUM (pi in healthy range, expect Kiryo to provide meaningful correction)"

    return (
        f"# Phase 3 EXP 3.1 — PU prior pi estimate\n\n"
        f"_Generated by `scripts/build_pu_prior.py` on {now}_\n\n"
        f"## Headline\n\n"
        f"**pi = {pi:.4f}**  (estimation method: `{method}`)\n\n"
        f"This is the value to pass to `KiryoPULoss(pi=...)` when "
        f"integrating into the Phase 3 training loop (E.3 in `master_checklist.txt`).\n\n"
        f"## Inputs\n\n"
        f"| Field | Value |\n"
        f"|---|---|\n"
        f"| train_dataset.json path | `{train_json_path}` |\n"
        f"| n_images | {extra_stats['n_images']:,} |\n"
        f"| n_annotations | {extra_stats['n_annotations']:,} |\n"
        f"| n_categories | {extra_stats['n_categories']:,} |\n\n"
        f"## Estimation method\n\n"
        f"- `area_fraction`: pi = mean over images of (sum of GT box pixel areas / image pixel area). "
        f"Best when 'positive anchor' means 'anchor overlaps a GT box,' which is the YOLO objectness setting.\n"
        f"- `annotation_rate`: pi = (n_annotations) / (n_images * 100). Approximates the fraction of "
        f"typical anchors (~100 per image) that are positive. Cruder, used as a sanity cross-check.\n\n"
        f"## Risk assessment\n\n"
        f"{risk}\n\n"
        f"## Recommended PU loss config\n\n"
        f"```python\n"
        f"from src.pu_loss import KiryoPULoss\n\n"
        f"pu_loss = KiryoPULoss(\n"
        f"    pi={pi:.4f},\n"
        f"    surrogate_loss='sigmoid',  # bounded; safer when pi is mis-estimated\n"
        f"    beta=0.0,                  # default Kiryo non-negative trick threshold\n"
        f"    gamma=1.0,                 # full gradient discount when correction fires\n"
        f"    reduction='mean',\n"
        f")\n"
        f"```\n\n"
        f"## Working notes paper hook\n\n"
        f"In the methodology section, cite this estimate as: 'Following Kiryo et al. (2017), "
        f"we estimate the positive-class prior pi from the training set's per-image area fraction "
        f"of GT bounding boxes, yielding pi = {pi:.4f} for FathomNet 2026.'\n"
    )


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Estimate the Kiryo PU class prior pi from train_dataset.json (Phase 3 EXP 3.1).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--train-json",
        type=Path,
        default=_REPO_ROOT / "data" / "raw" / "train_dataset.json",
    )
    p.add_argument(
        "--method",
        choices=("area_fraction", "annotation_rate"),
        default="area_fraction",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=_REPO_ROOT / "notes" / "phase3_pi_estimate.md",
    )
    p.add_argument("--quiet", action="store_true", help="Don't print the per-channel detail.")
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    if not args.train_json.exists():
        print(f"ERROR: train JSON not found at {args.train_json}", file=sys.stderr)
        return 2

    pi = estimate_pu_prior(args.train_json, method=args.method, verbose=not args.quiet)
    extra = _gather_per_image_stats(args.train_json)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    report = _format_report(pi, args.method, args.train_json, extra)
    args.out.write_text(report, encoding="utf-8")

    print(f"\nFinal pi = {pi:.4f}")
    print(f"Report written to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
