"""Capture YOLOv11m backbone P3/P4/P5 output shapes.

Block reference: D.3 in master_checklist.txt.

Why this matters
----------------
The BioCLIP2 -> YOLO adapter (D.4) projects ViT features into YOLO's neck
inputs. To do that, we need to know:
  1. How many channels does YOLOv11m's backbone produce at each scale?
  2. What are the spatial dimensions of those scales for both imgsz=640 and 1280?

Ultralytics' YOLOv11 follows the "P3/P4/P5" feature-pyramid convention:
  P3 at stride 8   -> small-object features
  P4 at stride 16  -> medium-object features
  P5 at stride 32  -> large-object features

This script forward-hooks the SPPF block (the last backbone module before
the neck) and the two preceding C2f blocks to extract those three pyramid
levels. Outputs a human-readable table to notes/yolo11m_backbone_shapes.txt
that D.4 can reference.

Usage
-----
    python scripts/inspect_yolo_backbone.py
    # or with a specific imgsz:
    python scripts/inspect_yolo_backbone.py --imgsz 640 1280 1024

The first run downloads yolo11m.pt (~40 MB) into the Ultralytics cache.
Subsequent runs are cached.

Output
------
Prints a table to stdout AND writes notes/yolo11m_backbone_shapes.txt
with the same content for posterity.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "notes" / "yolo11m_backbone_shapes.txt"

# YOLOv11 backbone in Ultralytics' default YAML has 11 blocks (indices 0-10).
# The three tensors that feed the neck are:
#   index  4  -> P3 (after the second C2f block, stride=8)
#   index  6  -> P4 (after the third C2f block,  stride=16)
#   index 10  -> P5 (after the SPPF block,       stride=32)
# These come from yolo11.yaml. We hook all three.
BACKBONE_TAP_INDICES = (4, 6, 10)
TAP_NAME_BY_INDEX = {4: "P3 (stride 8)", 6: "P4 (stride 16)", 10: "P5 (stride 32)"}


def inspect(imgszs: list[int], model_name: str = "yolo11m.pt") -> dict:
    """Return {imgsz: [(layer_idx, name, shape), ...]} for every requested size."""
    from ultralytics import YOLO

    print(f"Loading {model_name} ...")
    yolo = YOLO(model_name)
    # The actual nn.Module is yolo.model. yolo.model.model is the Sequential
    # of all 23 blocks (11 backbone + 12 neck/head for yolo11m).
    seq = yolo.model.model

    captures: dict[int, torch.Tensor] = {}

    def make_hook(idx: int):
        def hook(_module, _inp, out):
            captures[idx] = out.detach()
        return hook

    handles = []
    for idx in BACKBONE_TAP_INDICES:
        h = seq[idx].register_forward_hook(make_hook(idx))
        handles.append(h)

    yolo.model.eval()
    results: dict[int, list[tuple[int, str, tuple[int, ...]]]] = {}
    try:
        for imgsz in imgszs:
            captures.clear()
            x = torch.randn(1, 3, imgsz, imgsz)
            with torch.no_grad():
                _ = yolo.model(x)
            results[imgsz] = [
                (idx, TAP_NAME_BY_INDEX[idx], tuple(captures[idx].shape))
                for idx in BACKBONE_TAP_INDICES
            ]
    finally:
        for h in handles:
            h.remove()

    return results


def format_report(results: dict, model_name: str = "yolo11m") -> str:
    lines = [
        "=" * 72,
        f"YOLOv11 backbone shape inspection -- {model_name}",
        "Generated by scripts/inspect_yolo_backbone.py",
        "=" * 72,
        "",
        "Convention: backbone produces 3 feature maps that feed the neck.",
        "  P3 = small-object features  (stride 8)",
        "  P4 = medium-object features (stride 16)",
        "  P5 = large-object features  (stride 32)",
        "",
        "Tensor shape format: (batch, channels, height, width)",
        "",
    ]
    for imgsz, taps in results.items():
        lines.append(f"### Input size: {imgsz} x {imgsz}")
        lines.append("")
        lines.append(f"{'Layer idx':<10} {'Pyramid level':<20} {'Output shape':<30} {'Channels':<10} {'Spatial':<10}")
        lines.append("-" * 80)
        for idx, name, shape in taps:
            channels = shape[1]
            spatial = f"{shape[2]}x{shape[3]}"
            lines.append(f"{idx:<10} {name:<20} {str(shape):<30} {channels:<10} {spatial:<10}")
        lines.append("")

    lines += [
        "=" * 72,
        "BIOCLIP2 ADAPTER DESIGN IMPLICATIONS (D.4)",
        "=" * 72,
        "",
        "The adapter must take BioCLIP2 ViT-L/14 features (1024 channels at",
        "stride 14, single scale) and produce 3 tensors matching the channel",
        "counts and spatial dims above so they can be CONCATENATED with",
        "YOLO's own backbone outputs at the neck input.",
        "",
        "Per-scale adapter heads (one each for P3, P4, P5):",
        "  - 1x1 conv: 1024 -> target channel count (read from table above)",
        "  - bilinear interpolation: ViT spatial map -> P3/P4/P5 spatial dim",
        "  - zero-init the conv weights so the model starts ~ vanilla YOLO",
        "",
        "ViT spatial map at imgsz=640: 640/14 ~= 46x46 (positional-embed",
        "interpolation needed, since native ViT-L/14 was trained at 224x224",
        "= 16x16 patch grid).",
        "",
        "ViT spatial map at imgsz=1280: 1280/14 ~= 92x92.",
        "",
        "For both, P3 (80x80 at imgsz=640) is the closest spatial scale to",
        "the ViT output, so adapter for P3 mostly does channel projection.",
        "P4 and P5 require additional downsampling.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--imgsz",
        type=int,
        nargs="+",
        default=[640, 1280],
        help="Input sizes to inspect (default: 640 1280)",
    )
    parser.add_argument(
        "--model",
        default="yolo11m.pt",
        help="Ultralytics model to inspect (default: yolo11m.pt)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output report path (default: {DEFAULT_OUT.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args()

    results = inspect(args.imgsz, model_name=args.model)
    report = format_report(results, model_name=args.model.replace(".pt", ""))
    print(report)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")
    print(f"\nReport written to: {args.out}")


if __name__ == "__main__":
    main()
