"""Build per-fold YOLO data configs from cv_folds.pkl.

WHAT IT DOES:
    For each of the 5 stratified CV folds in data/cv_folds.pkl, emits:
      data/folds/fold{i}_train.txt   <- image paths in the fold's train set
      data/folds/fold{i}_val.txt     <- image paths in the fold's val set
      data/folds/fold{i}.yaml        <- Ultralytics-format dataset config

    All 5 YAMLs share:
      - the same `path:` (data/raw, where images/ and labels/ both live)
      - the same `names:` (32 entries, derived from train_dataset.json
        categories array, mapped through cat_id_to_idx so order matches
        what coco_to_yolo.py wrote into the .txt labels)
      - the same `nc:` (32)
    They differ ONLY in train/val pointers.

WHY YAMLS POINT AT .TXT FILES:
    Ultralytics supports two ways to specify train/val:
      (a) a directory containing images, OR
      (b) a .txt with one image path per line.
    We use (b) because we keep ONE shared images/ directory and slice it
    differently per fold. Symlinking (option a) wastes disk and doesn't
    work cleanly on Windows or in containers.

WHY image paths are RELATIVE to `path:`:
    Ultralytics resolves `path:` once, then prepends it to every line in
    the train/val .txt. Relative paths mean the same .txt files work on
    any machine (laptop, RunPod, Kaggle) by just changing `path:` -- we
    write `path:` as absolute on the local box, but you can override at
    training time with `data.path=/workspace/data/raw`.

WHY label discovery JUST WORKS:
    Ultralytics derives the label path by replacing "/images/" with
    "/labels/" in each image path. Since coco_to_yolo.py writes labels
    to data/raw/labels/train/<uuid>.txt, and images live at
    data/raw/images/train/<uuid>.{png,jpg}, the swap finds the right
    file every time.

USAGE:
    python scripts/make_yolo_fold.py
    python scripts/make_yolo_fold.py --dataset-path /workspace/data/raw

VERIFICATION:
    Prints per-fold train/val counts and a class name preview. Sanity-
    checks that every val image_id has at least one annotation file
    (since coco_to_yolo.py writes empty .txt for zero-ann images, this
    is automatic, but we verify the parent dirs exist).
"""
from __future__ import annotations

import argparse
import json
import pickle
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from configs.cat_id_mapping import cat_id_to_idx, idx_to_cat_id  # noqa: E402

DEFAULT_CV_FOLDS = REPO_ROOT / "data" / "cv_folds.pkl"
DEFAULT_TRAIN_JSON = REPO_ROOT / "data" / "raw" / "train_dataset.json"
DEFAULT_OUT_DIR = REPO_ROOT / "data" / "folds"
DEFAULT_DATASET_PATH = REPO_ROOT / "data" / "raw"
TRAIN_IMAGES_SUBDIR = "images/train"  # relative to dataset_path; matches label discovery


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--cv-folds", type=Path, default=DEFAULT_CV_FOLDS)
    p.add_argument("--train-json", type=Path, default=DEFAULT_TRAIN_JSON)
    p.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    p.add_argument(
        "--dataset-path",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help="Absolute path written into each YAML's `path:` field. Override "
             "to point at the dataset on RunPod / Kaggle.",
    )
    return p.parse_args()


def write_yaml(out_path: Path, dataset_path: Path, train_txt: Path, val_txt: Path,
               names: dict[int, str]) -> None:
    """Write a minimal Ultralytics-format YAML (no PyYAML dep needed).

    Hand-rolled instead of yaml.dump() to keep zero deps and produce a
    diff-friendly stable output. Names list is sorted by class_idx (0-31).
    """
    lines = [
        f"# Auto-generated by scripts/make_yolo_fold.py. Do not edit by hand.",
        f"# Override `path` at training time if your dataset moves.",
        f"path: {dataset_path.as_posix()}",
        f"train: {train_txt.relative_to(out_path.parent).as_posix()}",
        f"val: {val_txt.relative_to(out_path.parent).as_posix()}",
        f"nc: {len(names)}",
        f"names:",
    ]
    for idx in sorted(names):
        lines.append(f"  {idx}: {names[idx]}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()

    if not args.cv_folds.exists():
        print(f"ERROR: cv_folds.pkl not found at {args.cv_folds}", file=sys.stderr)
        return 2
    if not args.train_json.exists():
        print(f"ERROR: train_dataset.json not found at {args.train_json}", file=sys.stderr)
        return 2

    with args.cv_folds.open("rb") as f:
        cv = pickle.load(f)
    with args.train_json.open() as f:
        coco = json.load(f)

    image_id_to_filename = {int(img["id"]): img["file_name"] for img in coco["images"]}

    names: dict[int, str] = {}
    for cat in coco["categories"]:
        cat_id = int(cat["id"])
        if cat_id in cat_id_to_idx:
            names[cat_id_to_idx[cat_id]] = cat.get("name", f"cat_{cat_id}")
    if len(names) != 32:
        print(
            f"WARN: expected 32 class names, got {len(names)}. "
            f"Missing class_idx values: {sorted(set(idx_to_cat_id) - set(names))}",
            file=sys.stderr,
        )

    args.out_dir.mkdir(parents=True, exist_ok=True)

    n_folds = cv["n_folds"]
    print(f"Loaded {n_folds}-fold split from {args.cv_folds.name}")
    print(f"Dataset path (written into YAMLs): {args.dataset_path.as_posix()}")
    print(f"Image subdir (relative to path):   {TRAIN_IMAGES_SUBDIR}/")
    print(f"Output dir:                        {args.out_dir.relative_to(REPO_ROOT)}/\n")

    missing_filenames = 0
    for fold_dict in cv["folds"]:
        fold_idx = fold_dict["fold"]
        train_ids = fold_dict["train_image_ids"]
        val_ids = fold_dict["val_image_ids"]

        train_paths: list[str] = []
        val_paths: list[str] = []
        for img_id in train_ids:
            fn = image_id_to_filename.get(int(img_id))
            if fn is None:
                missing_filenames += 1
                continue
            train_paths.append(f"{TRAIN_IMAGES_SUBDIR}/{fn}")
        for img_id in val_ids:
            fn = image_id_to_filename.get(int(img_id))
            if fn is None:
                missing_filenames += 1
                continue
            val_paths.append(f"{TRAIN_IMAGES_SUBDIR}/{fn}")

        train_txt = args.out_dir / f"fold{fold_idx}_train.txt"
        val_txt = args.out_dir / f"fold{fold_idx}_val.txt"
        yaml_path = args.out_dir / f"fold{fold_idx}.yaml"

        train_txt.write_text("\n".join(train_paths) + "\n", encoding="utf-8")
        val_txt.write_text("\n".join(val_paths) + "\n", encoding="utf-8")
        write_yaml(yaml_path, args.dataset_path, train_txt, val_txt, names)

        print(f"fold {fold_idx}: train={len(train_paths):,}  val={len(val_paths):,}  -> {yaml_path.name}")

    if missing_filenames:
        print(f"\nWARN: {missing_filenames} image_ids in cv_folds.pkl had no matching "
              f"entry in train_dataset.json (skipped).", file=sys.stderr)

    print(f"\nClass names preview (idx -> name):")
    for idx in sorted(names)[:5]:
        print(f"  {idx}: {names[idx]}")
    print(f"  ... ({len(names)} total)")
    print(f"  {sorted(names)[-1]}: {names[sorted(names)[-1]]}")

    print(f"\nDone. To verify YOLO can load fold 0:")
    print(f"  python -c \"from ultralytics.data.utils import check_det_dataset; "
          f"check_det_dataset(r'{args.out_dir / 'fold0.yaml'}')\"")
    return 0


if __name__ == "__main__":
    sys.exit(main())
